/**
 * galaxy inc.
 * meetup client for android
 */
package com.galaxy.meetup.client.android.analytics;

import com.galaxy.meetup.server.client.domain.FavaDiagnosticsNamespacedType;

/**
 * 
 * @author sihai
 *
 */
public enum OzActions {

	EXIT("EXIT", 0, "natapp", Integer.valueOf(2)),
    LAUNCH("LAUNCH", 1, "natapp", Integer.valueOf(1)),
    SETTINGS_HELP("SETTINGS_HELP", 2, "Settings", Integer.valueOf(18)),
    SETTINGS_FEEDBACK("SETTINGS_FEEDBACK", 3, "Settings", Integer.valueOf(19)),
    SETTINGS_TOS("SETTINGS_TOS", 4, "Settings", Integer.valueOf(20)),
    SETTINGS_SIGNOUT("SETTINGS_SIGNOUT", 5, "Settings", Integer.valueOf(21)),
    LOOP_CHECKIN("LOOP_CHECKIN", 6, "ttn", Integer.valueOf(6)),
    STREAM_SELECT_ACTIVITY("STREAM_SELECT_ACTIVITY", 7, "str", Integer.valueOf(22)),
    STREAM_SELECT_AUTHOR("STREAM_SELECT_AUTHOR", 8, "pr", Integer.valueOf(4)),
    COMPOSE_POST("COMPOSE_POST", 9, "ttn", Integer.valueOf(4)),
    COMPOSE_CHANGE_ACL("COMPOSE_CHANGE_ACL", 10, "ttn", Integer.valueOf(94)),
    COMPOSE_ADD_VISIBILITY_ACL("COMPOSE_ADD_VISIBILITY_ACL", 11, "ttn", Integer.valueOf(11)),
    COMPOSE_REMOVE_VISIBILITY_ACL("COMPOSE_REMOVE_VISIBILITY_ACL", 12, "ttn", Integer.valueOf(12)),
    COMPOSE_ADD_CIRCLE_ACL("COMPOSE_ADD_CIRCLE_ACL", 13, "ttn", Integer.valueOf(13)),
    COMPOSE_REMOVE_CIRCLE_ACL("COMPOSE_REMOVE_CIRCLE_ACL", 14, "ttn", Integer.valueOf(14)),
    COMPOSE_ADD_INDIVIDUAL_ACL("COMPOSE_ADD_INDIVIDUAL_ACL", 15, "ttn", Integer.valueOf(15)),
    COMPOSE_REMOVE_INDIVIDUAL_ACL("COMPOSE_REMOVE_INDIVIDUAL_ACL", 16, "ttn", Integer.valueOf(16)),
    COMPOSE_CHANGE_LOCATION("COMPOSE_CHANGE_LOCATION", 17, "ttn", Integer.valueOf(6)),
    COMPOSE_TAKE_PHOTO("COMPOSE_TAKE_PHOTO", 18, "ttn", Integer.valueOf(95)),
    COMPOSE_CHOOSE_PHOTO("COMPOSE_CHOOSE_PHOTO", 19, "ttn", Integer.valueOf(7)),
    EMOTISHARE_INSERT_CLICKED("EMOTISHARE_INSERT_CLICKED", 20, "ttn", Integer.valueOf(106)),
    EMOTISHARE_SELECTED("EMOTISHARE_SELECTED", 21, "ttn", Integer.valueOf(107)),
    EMOTISHARE_REMOVED("EMOTISHARE_REMOVED", 22, "ttn", Integer.valueOf(108)),
    EMOTISHARE_TEXT_MODIFIED("EMOTISHARE_TEXT_MODIFIED", 23, "ttn", Integer.valueOf(109)),
    EMOTISHARE_TEXT_UNMODIFIED("EMOTISHARE_TEXT_UNMODIFIED", 24, "ttn", Integer.valueOf(110)),
    PROFILE_EDIT_START("PROFILE_EDIT_START", 25, "pr", Integer.valueOf(1)),
    PROFILE_EDIT_SAVE("PROFILE_EDIT_SAVE", 26, "pr", Integer.valueOf(2)),
    PROFILE_EDIT_CANCEL("PROFILE_EDIT_CANCEL", 27, "pr", Integer.valueOf(3)),
    COVER_PHOTO_UPGRADE_START("COVER_PHOTO_UPGRADE_START", 28, "pr", Integer.valueOf(39)),
    COVER_PHOTO_UPGRADE_OK("COVER_PHOTO_UPGRADE_OK", 29, "pr", Integer.valueOf(40)),
    COVER_PHOTO_UPGRADE_CANCEL("COVER_PHOTO_UPGRADE_CANCEL", 30, "pr", Integer.valueOf(41)),
    COVER_PHOTO_CHANGE("COVER_PHOTO_CHANGE", 31, "pr", Integer.valueOf(30)),
    COVER_PHOTO_CHOOSE_OWN_PHOTO("COVER_PHOTO_CHOOSE_OWN_PHOTO", 32, "pr", Integer.valueOf(42)),
    COVER_PHOTO_CHOOSE_GALLERY("COVER_PHOTO_CHOOSE_GALLERY", 33, "pr", Integer.valueOf(43)),
    COVER_PHOTO_REPOSITION("COVER_PHOTO_REPOSITION", 34, "pr", Integer.valueOf(36)),
    ONE_UP_SELECT_AUTHOR("ONE_UP_SELECT_AUTHOR", 35, "pr", Integer.valueOf(4)),
    ONE_UP_SELECT_PERSON("ONE_UP_SELECT_PERSON", 36, "pr", Integer.valueOf(5)),
    ONE_UP_SELECT_PHOTO("ONE_UP_SELECT_PHOTO", 37, "str", Integer.valueOf(52)),
    ONE_UP_POST_COMMENT("ONE_UP_POST_COMMENT", 38, "str", Integer.valueOf(2)),
    OPEN_RESHARE_SHAREBOX("OPEN_RESHARE_SHAREBOX", 39, "str", Integer.valueOf(16)),
    RESHARE("RESHARE", 40, "str", Integer.valueOf(17)),
    ONE_UP_REMOVE_ACTIVITY("ONE_UP_REMOVE_ACTIVITY", 41, "str", Integer.valueOf(8)),
    ONE_UP_MUTE_ACTIVITY("ONE_UP_MUTE_ACTIVITY", 42, "str", Integer.valueOf(5)),
    ONE_UP_REPORT_ABUSE_ACTIVITY("ONE_UP_REPORT_ABUSE_ACTIVITY", 43, "str", Integer.valueOf(25)),
    ONE_UP_MARK_ACTIVITY_AS_READ("ONE_UP_MARK_ACTIVITY_AS_READ", 44, "str", Integer.valueOf(57)),
    STREAM_MARK_ACTIVITY_AS_READ("STREAM_MARK_ACTIVITY_AS_READ", 45, "str", Integer.valueOf(57)),
    STREAM_SHARE_INSTANT_UPLOAD_PHOTOS("STREAM_SHARE_INSTANT_UPLOAD_PHOTOS", 46, "str", Integer.valueOf(94)),
    STREAM_DISMISS_INSTANT_UPLOAD_PHOTOS("STREAM_DISMISS_INSTANT_UPLOAD_PHOTOS", 47, "str", Integer.valueOf(95)),
    ONE_UP_REPORT_ABUSE_COMMENT("ONE_UP_REPORT_ABUSE_COMMENT", 48, "str", Integer.valueOf(25)),
    ONE_UP_OPEN_REPORT_ABUSE_COMMENT("ONE_UP_OPEN_REPORT_ABUSE_COMMENT", 49, "str", Integer.valueOf(19)),
    ONE_UP_CANCEL_REPORT_ABUSE_COMMENT("ONE_UP_CANCEL_REPORT_ABUSE_COMMENT", 50, "str", Integer.valueOf(26)),
    ONE_UP_DELETE_COMMENT("ONE_UP_DELETE_COMMENT", 51, "str", Integer.valueOf(9)),
    ONE_UP_EDIT_COMMENT("ONE_UP_EDIT_COMMENT", 52, "str", Integer.valueOf(7)),
    OPEN_URL("OPEN_URL", 53, "str", Integer.valueOf(14)),
    PHOTOS_SURPRISE_CAID("PHOTOS_SURPRISE_CAID", 54, "phst", Integer.valueOf(59)),
    CONVERSATIONS_START_NEW("CONVERSATIONS_START_NEW", 55, "messenger", Integer.valueOf(1)),
    CONVERSATION_ABORT_NEW("CONVERSATION_ABORT_NEW", 56, "messenger", Integer.valueOf(2)),
    CONVERSATION_RETRY_SEND("CONVERSATION_RETRY_SEND", 57, "messenger", Integer.valueOf(3)),
    GROUP_CONVERSATION_POST("GROUP_CONVERSATION_POST", 58, "messenger", Integer.valueOf(4)),
    GROUP_CONVERSATION_TAKE_PHOTO("GROUP_CONVERSATION_TAKE_PHOTO", 59, "messenger", Integer.valueOf(5)),
    GROUP_CONVERSATION_CHOOSE_PHOTO("GROUP_CONVERSATION_CHOOSE_PHOTO", 60, "messenger", Integer.valueOf(6)),
    GROUP_CONVERSATION_MUTE("GROUP_CONVERSATION_MUTE", 61, "messenger", Integer.valueOf(7)),
    GROUP_CONVERSATION_UNMUTE("GROUP_CONVERSATION_UNMUTE", 62, "messenger", Integer.valueOf(8)),
    GROUP_CONVERSATION_ADD_PEOPLE("GROUP_CONVERSATION_ADD_PEOPLE", 63, "messenger", Integer.valueOf(9)),
    GROUP_CONVERSATION_MAKE_CIRCLE("GROUP_CONVERSATION_MAKE_CIRCLE", 64, "messenger", Integer.valueOf(10)),
    GROUP_CONVERSATION_LEAVE("GROUP_CONVERSATION_LEAVE", 65, "messenger", Integer.valueOf(11)),
    GROUP_CONVERSATION_RENAME("GROUP_CONVERSATION_RENAME", 66, "messenger", Integer.valueOf(12)),
    ONE_ON_ONE_CONVERSATION_POST("ONE_ON_ONE_CONVERSATION_POST", 67, "messenger", Integer.valueOf(13)),
    ONE_ON_ONE_CONVERSATION_TAKE_PHOTO("ONE_ON_ONE_CONVERSATION_TAKE_PHOTO", 68, "messenger", Integer.valueOf(14)),
    ONE_ON_ONE_CONVERSATION_CHOOSE_PHOTO("ONE_ON_ONE_CONVERSATION_CHOOSE_PHOTO", 69, "messenger", Integer.valueOf(15)),
    ONE_ON_ONE_CONVERSATION_MUTE("ONE_ON_ONE_CONVERSATION_MUTE", 70, "messenger", Integer.valueOf(16)),
    ONE_ON_ONE_CONVERSATION_UNMUTE("ONE_ON_ONE_CONVERSATION_UNMUTE", 71, "messenger", Integer.valueOf(17)),
    ONE_ON_ONE_CONVERSATION_ADD_PEOPLE("ONE_ON_ONE_CONVERSATION_ADD_PEOPLE", 72, "messenger", Integer.valueOf(18)),
    CS_SETTINGS_OPTED_IN("CS_SETTINGS_OPTED_IN", 73, "Settings", Integer.valueOf(3)),
    CS_SETTINGS_OPTED_OUT("CS_SETTINGS_OPTED_OUT", 74, "Settings", Integer.valueOf(4)),
    CS_SETTINGS_SYNC_ALL("CS_SETTINGS_SYNC_ALL", 75, "Settings", Integer.valueOf(5)),
    CS_SETTINGS_UPLOAD_VIA_VIDEOS_VIA_MOBILE("CS_SETTINGS_UPLOAD_VIA_VIDEOS_VIA_MOBILE", 76, "Settings", Integer.valueOf(8)),
    CS_SETTINGS_UPLOAD_VIA_VIDEOS_VIA_WIFI_ONLY("CS_SETTINGS_UPLOAD_VIA_VIDEOS_VIA_WIFI_ONLY", 77, "Settings", Integer.valueOf(9)),
    CS_SETTINGS_UPLOAD_VIA_PHOTOS_AND_VIDEOS_VIA_MOBILE("CS_SETTINGS_UPLOAD_VIA_PHOTOS_AND_VIDEOS_VIA_MOBILE", 78, "Settings", Integer.valueOf(10)),
    CS_SETTINGS_UPLOAD_VIA_PHOTOS_AND_VIDEOS_VIA_WIFI_ONLY("CS_SETTINGS_UPLOAD_VIA_PHOTOS_AND_VIDEOS_VIA_WIFI_ONLY", 79, "Settings", Integer.valueOf(11)),
    CS_SETTINGS_ROAMING_ENABLED("CS_SETTINGS_ROAMING_ENABLED", 80, "Settings", Integer.valueOf(12)),
    CS_SETTINGS_ROAMING_DISABLED("CS_SETTINGS_ROAMING_DISABLED", 81, "Settings", Integer.valueOf(13)),
    ENABLE_STANDARD_SIZE_PHOTO_UPLOAD("ENABLE_STANDARD_SIZE_PHOTO_UPLOAD", 82, "Settings", Integer.valueOf(26)),
    ENABLE_FULL_SIZE_PHOTO_UPLOAD("ENABLE_FULL_SIZE_PHOTO_UPLOAD", 83, "Settings", Integer.valueOf(27)),
    PLATFORM_CLICKED_PLUSONE("PLATFORM_CLICKED_PLUSONE", 84, "plusone", Integer.valueOf(9)),
    PLATFORM_PLUSONE_CONFIRMED("PLATFORM_PLUSONE_CONFIRMED", 85, "plusone", Integer.valueOf(10)),
    PLATFORM_PLUSONE_CANCELED("PLATFORM_PLUSONE_CANCELED", 86, "plusone", Integer.valueOf(11)),
    PLATFORM_UNDO_PLUSONE_CONFIRMED("PLATFORM_UNDO_PLUSONE_CONFIRMED", 87, "plusone", Integer.valueOf(12)),
    PLATFORM_UNDO_PLUSONE_CANCELED("PLATFORM_UNDO_PLUSONE_CANCELED", 88, "plusone", Integer.valueOf(13)),
    PLATFORM_READ_PLUSONES("PLATFORM_READ_PLUSONES", 89, "plusone", Integer.valueOf(6)),
    PLATFORM_READ_PLUSONES_ERROR("PLATFORM_READ_PLUSONES_ERROR", 90, "plusone", Integer.valueOf(15)),
    PLATFORM_WRITE_PLUSONE("PLATFORM_WRITE_PLUSONE", 91, "plusone", Integer.valueOf(16)),
    PLATFORM_WRITE_PLUSONE_ERROR("PLATFORM_WRITE_PLUSONE_ERROR", 92, "plusone", Integer.valueOf(17)),
    PLATFORM_ERROR_PLUSONE("PLATFORM_ERROR_PLUSONE", 93, "plusone", Integer.valueOf(18)),
    PLATFORM_PLUSONE_PREVIEW_SHOWN("PLATFORM_PLUSONE_PREVIEW_SHOWN", 94, "plusone", Integer.valueOf(19)),
    PLATFORM_OPEN_SHAREBOX("PLATFORM_OPEN_SHAREBOX", 95, "ttn", Integer.valueOf(4)),
    PLATFORM_CONFIRM_SHARE("PLATFORM_CONFIRM_SHARE", 96, "ttn", Integer.valueOf(8)),
    PLATFORM_CANCEL_SHARE("PLATFORM_CANCEL_SHARE", 97, "ttn", Integer.valueOf(2)),
    PLATFORM_CONFIRM_SHARE_FROM_PLUSONE("PLATFORM_CONFIRM_SHARE_FROM_PLUSONE", 98, "ttn", Integer.valueOf(4)),
    PLATFORM_CANCEL_SHARE_FROM_PLUSONE("PLATFORM_CANCEL_SHARE_FROM_PLUSONE", 99, "ttn", Integer.valueOf(2)),
    PLATFORM_CLICKED_SHARE_FROM_PLUSONE("PLATFORM_CLICKED_SHARE_FROM_PLUSONE", 100, "ttn", Integer.valueOf(4)),
    PLATFORM_ERROR_SHARE("PLATFORM_ERROR_SHARE", 101, "ttn", Integer.valueOf(47)),
    PLATFORM_SHARE_PREVIEW_SHOWN("PLATFORM_SHARE_PREVIEW_SHOWN", 102, "ttn", Integer.valueOf(89)),
    PLATFORM_SHARE_PREVIEW_ERROR("PLATFORM_SHARE_PREVIEW_ERROR", 103, "ttn", Integer.valueOf(90)),
    PLATFORM_SHARE_COMMENT_ADDED("PLATFORM_SHARE_COMMENT_ADDED", 104, "ttn", Integer.valueOf(91)),
    PLATFORM_SHARE_POST_ERROR("PLATFORM_SHARE_POST_ERROR", 105, "ttn", Integer.valueOf(47)),
    PLATFORM_SHARE_POST_WITH_ATTACHMENT("PLATFORM_SHARE_POST_WITH_ATTACHMENT", 106, "ttn", Integer.valueOf(5)),
    PLATFORM_SHARE_POST_WITH_COMMENT("PLATFORM_SHARE_POST_WITH_COMMENT", 107, "ttn", Integer.valueOf(21)),
    PLATFORM_SHARE_POST_WITH_LOCATION("PLATFORM_SHARE_POST_WITH_LOCATION", 108, "ttn", Integer.valueOf(21)),
    PLATFORM_SHARE_POST_WITH_URL("PLATFORM_SHARE_POST_WITH_URL", 109, "ttn", Integer.valueOf(21)),
    PLATFORM_SHARE_POST_WITH_DEEP_LINK("PLATFORM_SHARE_POST_WITH_DEEP_LINK", 110, "ttn", Integer.valueOf(21)),
    PLATFORM_CIRCLES_SHARE_ACL_ADDED("PLATFORM_CIRCLES_SHARE_ACL_ADDED", 111, "ttn", Integer.valueOf(13)),
    PLATFORM_PEOPLE_SHARE_ACL_ADDED("PLATFORM_PEOPLE_SHARE_ACL_ADDED", 112, "ttn", Integer.valueOf(11)),
    PLATFORM_GET_ACCOUNT("PLATFORM_GET_ACCOUNT", 113, "signin", Integer.valueOf(2)),
    PLATFORM_SHARE_CLICKED_LOCATION("PLATFORM_SHARE_CLICKED_LOCATION", 114, "ttn", Integer.valueOf(93)),
    PLATFORM_SHARE_CLICKED_ACL("PLATFORM_SHARE_CLICKED_ACL", 115, "ttn", Integer.valueOf(94)),
    PLATFORM_SHARE_CLICKED_CAMERA("PLATFORM_SHARE_CLICKED_CAMERA", 116, "ttn", Integer.valueOf(7)),
    PLATFORM_SHARE_CLICKED_GALLERY("PLATFORM_SHARE_CLICKED_GALLERY", 117, "ttn", Integer.valueOf(7)),
    PLATFORM_CONNECT_SHOW_OOB("PLATFORM_CONNECT_SHOW_OOB", 118, "oob", Integer.valueOf(1)),
    PLATFORM_CONNECT_SELECT_ACCOUNT("PLATFORM_CONNECT_SELECT_ACCOUNT", 119, "oob", Integer.valueOf(41)),
    PLATFORM_AUDIENCE_VIEW_CLICKED("PLATFORM_AUDIENCE_VIEW_CLICKED", 120, "ttn", Integer.valueOf(63)),
    PLATFORM_AUDIENCE_VIEW_CIRCLE_ADDED("PLATFORM_AUDIENCE_VIEW_CIRCLE_ADDED", 121, "ttn", Integer.valueOf(13)),
    PLATFORM_AUDIENCE_VIEW_PERSON_ADDED("PLATFORM_AUDIENCE_VIEW_PERSON_ADDED", 122, "pr", Integer.valueOf(4)),
    CAMERA_SYNC_ENABLED("CAMERA_SYNC_ENABLED", 123, "Settings", Integer.valueOf(16)),
    CAMERA_SYNC_DISABLED("CAMERA_SYNC_DISABLED", 124, "Settings", Integer.valueOf(17)),
    CAMERA_SYNC_OPTED_IN("CAMERA_SYNC_OPTED_IN", 125, "oob", Integer.valueOf(34)),
    CAMERA_SYNC_WIFI_ONLY_OPTED_IN("CAMERA_SYNC_WIFI_ONLY_OPTED_IN", 126, "oob", Integer.valueOf(35)),
    CAMERA_SYNC_OPTED_OUT("CAMERA_SYNC_OPTED_OUT", 127, "oob", Integer.valueOf(36)),
    CONVERSATIONS_EMPTY("CONVERSATIONS_EMPTY", 128, "messenger", Integer.valueOf(19)),
    CONVERSATION_AUTO_RETRY_SUCCESS("CONVERSATION_AUTO_RETRY_SUCCESS", 129, "messenger", Integer.valueOf(20)),
    CONVERSATION_AUTO_RETRY_FAIL("CONVERSATION_AUTO_RETRY_FAIL", 130, "messenger", Integer.valueOf(21)),
    CONVERSATION_MANUAL_RETRY_FAIL("CONVERSATION_MANUAL_RETRY_FAIL", 131, "messenger", Integer.valueOf(22)),
    CONVERSATION_MANUAL_RETRY_SUCCESS("CONVERSATION_MANUAL_RETRY_SUCCESS", 132, "messenger", Integer.valueOf(23)),
    C2DM_MESSAGE_RECEIVED("C2DM_MESSAGE_RECEIVED", 133, "messenger", Integer.valueOf(24)),
    MESSAGE_RECEIVED("MESSAGE_RECEIVED", 134, "messenger", Integer.valueOf(25)),
    EVENTS_PARTY_MODE_ON("EVENTS_PARTY_MODE_ON", 135, "oevt", Integer.valueOf(58)),
    EVENTS_PARTY_MODE_OFF("EVENTS_PARTY_MODE_OFF", 136, "oevt", Integer.valueOf(59)),
    DEEP_LINK_INSTALL_OFFERED("DEEP_LINK_INSTALL_OFFERED", 137, "dl", Integer.valueOf(4)),
    DEEP_LINK_INSTALL_DECLINED("DEEP_LINK_INSTALL_DECLINED", 138, "dl", Integer.valueOf(5)),
    DEEP_LINK_INSTALL_ACCEPTED("DEEP_LINK_INSTALL_ACCEPTED", 139, "dl", Integer.valueOf(6)),
    DEEP_LINK_CLICKED_BUT_PLAY_STORE_NOT_INSTALLED("DEEP_LINK_CLICKED_BUT_PLAY_STORE_NOT_INSTALLED", 140, "dl", Integer.valueOf(7)),
    DEEP_LINK_CONSUMED("DEEP_LINK_CONSUMED", 141, "dl", Integer.valueOf(8)),
    DEEP_LINK_UNRESOLVED("DEEP_LINK_UNRESOLVED", 142, "dl", Integer.valueOf(9)),
    DEEP_LINK_INSTALL_STARTED_ON_PLAY_STORE("DEEP_LINK_INSTALL_STARTED_ON_PLAY_STORE", 143, "dl", Integer.valueOf(11)),
    DEEP_LINK_INSTALL_NOT_STARTED_ON_PLAY_STORE("DEEP_LINK_INSTALL_NOT_STARTED_ON_PLAY_STORE", 144, "dl", Integer.valueOf(12)),
    DEEP_LINK_INSTALL_COMPLETED_NOTIFICATION("DEEP_LINK_INSTALL_COMPLETED_NOTIFICATION", 145, "dl", Integer.valueOf(13)),
    CALL_TO_ACTION_INSTALL_ACCEPTED("CALL_TO_ACTION_INSTALL_ACCEPTED", 146, "dl", Integer.valueOf(14)),
    CALL_TO_ACTION_CLICKED_BUT_PLAY_STORE_NOT_INSTALLED("CALL_TO_ACTION_CLICKED_BUT_PLAY_STORE_NOT_INSTALLED", 147, "dl", Integer.valueOf(15)),
    CALL_TO_ACTION_CONSUMED("CALL_TO_ACTION_CONSUMED", 148, "dl", Integer.valueOf(16)),
    CALL_TO_ACTION_UNRESOLVED("CALL_TO_ACTION_UNRESOLVED", 149, "dl", Integer.valueOf(17)),
    CALL_TO_ACTION_INSTALL_STARTED_ON_PLAY_STORE("CALL_TO_ACTION_INSTALL_STARTED_ON_PLAY_STORE", 150, "dl", Integer.valueOf(18)),
    CALL_TO_ACTION_INSTALL_NOT_STARTED_ON_PLAY_STORE("CALL_TO_ACTION_INSTALL_NOT_STARTED_ON_PLAY_STORE", 151, "dl", Integer.valueOf(19)),
    CALL_TO_ACTION_INSTALL_COMPLETED_NOTIFICATION("CALL_TO_ACTION_INSTALL_COMPLETED_NOTIFICATION", 152, "dl", Integer.valueOf(20)),
    TICKLE_NOTIFICATION_RECEIVED("TICKLE_NOTIFICATION_RECEIVED", 153, "nots", Integer.valueOf(25)),
    TICKLE_EVENT_RECEIVED("TICKLE_EVENT_RECEIVED", 154, "nots", Integer.valueOf(26)),
    NOTIFICATION_FETCHED_FROM_TICKLE("NOTIFICATION_FETCHED_FROM_TICKLE", 155, "nots", Integer.valueOf(23)),
    NOTIFICATION_FETCHED_FROM_USER_REFRESH("NOTIFICATION_FETCHED_FROM_USER_REFRESH", 156, "nots", Integer.valueOf(24)),
    AGGREGATED_NOTIFICATION_CLICKED("AGGREGATED_NOTIFICATION_CLICKED", 157, "nots", Integer.valueOf(1)),
    SINGLE_NOTIFICATION_CLICKED("SINGLE_NOTIFICATION_CLICKED", 158, "nots", Integer.valueOf(3)),
    SHARE_INSTANT_UPLOAD_FROM_NOTIFICATION("SHARE_INSTANT_UPLOAD_FROM_NOTIFICATION", 159, "phst", Integer.valueOf(63)),
    ADD_CIRCLE_MEMBERS("ADD_CIRCLE_MEMBERS", 160, "sg", Integer.valueOf(12)),
    REMOVE_CIRCLE_MEMBERS("REMOVE_CIRCLE_MEMBERS", 161, "sg", Integer.valueOf(13)),
    SQUARE_APPLY_TO_JOIN("SQUARE_APPLY_TO_JOIN", 162, "sq", Integer.valueOf(17)),
    SQUARE_ACCEPT_INVITATION("SQUARE_ACCEPT_INVITATION", 163, "sq", Integer.valueOf(19)),
    SQUARE_JOIN("SQUARE_JOIN", 164, "sq", Integer.valueOf(20)),
    SQUARE_LEAVE("SQUARE_LEAVE", 165, "sq", Integer.valueOf(22)),
    SQUARE_SUBSCRIBE("SQUARE_SUBSCRIBE", 166, "sq", Integer.valueOf(32)),
    SQUARE_UNSUBSCRIBE("SQUARE_UNSUBSCRIBE", 167, "sq", Integer.valueOf(33)),
    SQUARE_APPLY_TO_JOIN_WITH_SUBSCRIPTION("SQUARE_APPLY_TO_JOIN_WITH_SUBSCRIPTION", 168, "sq", Integer.valueOf(34)),
    SQUARE_ACCEPT_INVITATION_WITH_SUBSCRIPTION("SQUARE_ACCEPT_INVITATION_WITH_SUBSCRIPTION", 169, "sq", Integer.valueOf(35)),
    SQUARE_JOIN_WITH_SUBSCRIPTION("SQUARE_JOIN_WITH_SUBSCRIPTION", 170, "sq", Integer.valueOf(36)),
    SQUARE_CANCEL_JOIN_REQUEST("SQUARE_CANCEL_JOIN_REQUEST", 171, "sq", Integer.valueOf(44)),
    SQUARE_DECLINE_INVITATION("SQUARE_DECLINE_INVITATION", 172, "sq", Integer.valueOf(45)),
    ENABLE_IMPROVE_SUGGESTIONS("ENABLE_IMPROVE_SUGGESTIONS", 173, "Settings", Integer.valueOf(22)),
    DISABLE_IMPROVE_SUGGESTIONS("DISABLE_IMPROVE_SUGGESTIONS", 174, "Settings", Integer.valueOf(23)),
    ENABLE_FIND_BY_PHONE_NUMBER("ENABLE_FIND_BY_PHONE_NUMBER", 175, "Settings", Integer.valueOf(24)),
    DISABLE_FIND_BY_PHONE_NUMBER("DISABLE_FIND_BY_PHONE_NUMBER", 176, "Settings", Integer.valueOf(25));
    
	private final FavaDiagnosticsNamespacedType mFavaDiagnosticsNamespacedType;
	
	private OzActions(String s, int i, String s1, Integer integer) {
        this(s, i, s1, integer, null);
    }

    private OzActions(String s, int i, String s1, Integer integer, String s2) {
        mFavaDiagnosticsNamespacedType = new FavaDiagnosticsNamespacedType();
        mFavaDiagnosticsNamespacedType.namespace = s1;
        mFavaDiagnosticsNamespacedType.typeNum = integer;
        mFavaDiagnosticsNamespacedType.typeStr = null;
    }
    
    public static String getName(OzActions ozactions) {
        String s;
        if(ozactions == null)
            s = null;
        else
            s = ozactions.name();
        return s;
    }

    public final FavaDiagnosticsNamespacedType getFavaDiagnosticsNamespacedType() {
        return mFavaDiagnosticsNamespacedType;
    }
}
